<?php

declare(strict_types=1);

namespace App\Modules\Manufacturing\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Response;

/**
 * Serves `/floor/sw.js`.
 *
 * A route rather than a file in `public/` for two reasons. A service worker may only control
 * paths below the directory it is served from, so anything Vite emitted under `/build/` could
 * never claim `/floor` — and the worker has to name the exact hashed files it precaches,
 * which only the build manifest knows.
 *
 * The body is `resources/js/floor/sw.js` with a `PRECACHE` list and a `VERSION` prepended. The
 * version is a hash of both, so a deploy that changes either gives the browser a byte-different
 * worker, which is the only thing that makes it install a new one.
 */
class ServiceWorkerController extends Controller
{
    /**
     * What the terminal needs on a device with no link: the entry bundle, the stylesheet with
     * its Bengali and Latin faces, and all three floor screens — including the ones the
     * operator has not opened yet, because the first tap after an outage starts is exactly
     * when the operation screen gets loaded for the first time.
     */
    private const ENTRIES = [
        'resources/js/app.js',
        'resources/css/app.css',
        'resources/js/Pages/Floor/Login.vue',
        'resources/js/Pages/Floor/Queue.vue',
        'resources/js/Pages/Floor/Operation.vue',
    ];

    public function __invoke(): Response
    {
        $source = (string) file_get_contents(resource_path('js/floor/sw.js'));
        $precache = $this->precache();

        // No manifest means `npm run dev`: assets are coming from the Vite dev server on
        // another port and there is nothing stable to cache. A developer who installed the
        // worker once would otherwise be served yesterday's bundle for as long as they kept
        // the tab open, with no obvious cause — so hand back a worker that removes itself.
        $body = $precache === null
            ? $this->selfDestruct()
            : $this->preamble($precache).$source;

        return response($body, 200, [
            'Content-Type' => 'application/javascript; charset=utf-8',
            // Revalidate every time. A worker cached for even an hour is a deploy that does
            // not reach the floor for an hour.
            'Cache-Control' => 'no-cache, must-revalidate',
            /*
             * Without this the browser caps the worker at the directory it was served from —
             * `/floor/`, with the trailing slash — and refuses to register it for `/floor`,
             * which is the badge screen and the manifest's own `start_url`. Registration fails
             * outright with a SecurityError, so the terminal keeps working online and silently
             * has no offline behaviour at all.
             */
            'Service-Worker-Allowed' => '/floor',
        ]);
    }

    /** @param  list<string>  $precache */
    private function preamble(array $precache): string
    {
        $version = substr(hash('xxh128', implode('|', $precache)), 0, 12);

        return sprintf(
            "// Generated by ServiceWorkerController — edit resources/js/floor/sw.js instead.\nconst VERSION = %s;\nconst PRECACHE = %s;\n\n",
            json_encode($version),
            json_encode($precache, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES),
        );
    }

    /**
     * The transitive closure of {@see self::ENTRIES} over the manifest — a chunk's own file,
     * the chunks it imports, the stylesheets it pulls in and the font files those reference.
     * Miss one and the worker installs cleanly and then fails on the reload it exists for.
     *
     * @return list<string>|null null when there is no build to cache.
     */
    private function precache(): ?array
    {
        $path = public_path('build/manifest.json');

        if (! is_file($path)) {
            return null;
        }

        /** @var array<string, array<string, mixed>> $manifest */
        $manifest = json_decode((string) file_get_contents($path), true) ?: [];

        $files = [];
        $seen = [];
        $pending = self::ENTRIES;

        while ($pending !== []) {
            $key = array_shift($pending);

            if (isset($seen[$key]) || ! isset($manifest[$key])) {
                continue;
            }

            $seen[$key] = true;
            $chunk = $manifest[$key];

            if (is_string($chunk['file'] ?? null)) {
                $files[] = '/build/'.$chunk['file'];
            }

            foreach (['css', 'assets'] as $list) {
                foreach ((array) ($chunk[$list] ?? []) as $file) {
                    $files[] = '/build/'.$file;
                }
            }

            foreach ((array) ($chunk['imports'] ?? []) as $import) {
                $pending[] = $import;
            }
        }

        $files = array_values(array_unique($files));
        sort($files);

        return $files;
    }

    /**
     * Unregisters and drops everything it cached. Served in development, where a stale worker
     * is all cost and no benefit.
     */
    private function selfDestruct(): string
    {
        return <<<'JS'
        // No build manifest — `npm run dev` is serving assets. Nothing here is worth caching.
        self.addEventListener('install', () => self.skipWaiting());
        self.addEventListener('activate', (event) => {
            event.waitUntil((async () => {
                const keys = await caches.keys();
                await Promise.all(keys.filter((key) => key.startsWith('octa-floor-')).map((key) => caches.delete(key)));
                await self.registration.unregister();
            })());
        });
        JS;
    }
}
